# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.DateTimeField()),
                ('horaSaida', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.DateTimeField()),
                ('horaSaida', models.DateTimeField()),
                ('status', models.BooleanField(verbose_name='status')),
                ('justificativa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('cpf', models.CharField(max_length=12, verbose_name='cpf')),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='Funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontoE.Funcionario'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='Funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontoE.Funcionario'),
        ),
    ]
