# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontoE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='status',
            field=models.CharField(choices=[('CO', 'Consistente'), ('IN', 'Inconsistente')], default='IN', max_length=2),
        ),
    ]
